#!/usr/bin/env python3
"""Fill visible publisher form fields from a prepared browser-publish payload."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import date
from pathlib import Path
from typing import Any
from urllib.parse import urlparse


ROOT = Path(__file__).resolve().parents[1]
TODAY = date.today().isoformat()
USER_AGENT = "Mozilla/5.0 (compatible; ViralProductPromotionSkill/1.0; +https://github.com/hqwzhu/Viral-Product-Copy-Video-Generator)"


def main() -> None:
    args = parse_args()
    out_dir = Path(args.out_dir)
    payload_path = Path(args.payload_json)
    payload_doc = read_payload(payload_path)
    issues = validate_payload(payload_doc, allow_localhost=args.allow_localhost)
    if issues:
        report = blocked_report(payload_doc, payload_path, issues)
    else:
        report = fill_form(args, payload_doc, payload_path, out_dir)
    write_report(out_dir, report)
    print(f"Browser form-fill report written to: {(report_dir(out_dir) / 'browser-form-fill.json').resolve()}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Fill visible creator publish form fields, then stop before final publish.")
    parser.add_argument("--payload-json", required=True, help="Payload JSON generated by browser_publish_assistant.py.")
    parser.add_argument("--out-dir", default="./promotion-output")
    parser.add_argument("--timeout-ms", type=int, default=30000)
    parser.add_argument("--wait-until", default="domcontentloaded", choices=["load", "domcontentloaded", "networkidle"])
    parser.add_argument("--headed", action="store_true", help="Show the browser while filling fields.")
    parser.add_argument("--allow-localhost", action="store_true", help="Allow localhost URLs for tests and local fixtures.")
    parser.add_argument("--install-browser-if-missing", action="store_true", help="Run the official Playwright Chromium install if missing.")
    return parser.parse_args()


def read_payload(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise SystemExit(f"Payload JSON not found: {path}")
    data = json.loads(path.read_text(encoding="utf-8-sig"))
    if not isinstance(data, dict):
        raise SystemExit("Payload JSON must contain an object.")
    return data


def validate_payload(payload_doc: dict[str, Any], allow_localhost: bool) -> list[str]:
    issues: list[str] = []
    url = clean_text(payload_doc.get("publisherUrl"))
    if not url:
        issues.append("missing_publisher_url")
    else:
        parsed = urlparse(url)
        if parsed.scheme not in {"http", "https"}:
            issues.append("unsupported_publisher_url_scheme")
        if is_local_url(parsed) and not allow_localhost:
            issues.append("localhost_requires_allow_localhost")
    payload = payload_doc.get("payload")
    if not isinstance(payload, dict):
        issues.append("missing_payload_object")
    return issues


def fill_form(args: argparse.Namespace, payload_doc: dict[str, Any], payload_path: Path, out_dir: Path) -> dict[str, Any]:
    try:
        from playwright.sync_api import Error as PlaywrightError
        from playwright.sync_api import TimeoutError as PlaywrightTimeoutError
        from playwright.sync_api import sync_playwright
    except Exception as exc:  # noqa: BLE001 - CLI reports optional dependency gaps.
        return error_report(payload_doc, payload_path, f"Playwright is not installed: {exc}")

    screenshot_path = report_dir(out_dir) / "browser-form-fill.png"
    screenshot_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        with sync_playwright() as playwright:
            browser = playwright.chromium.launch(headless=not args.headed)
            page = browser.new_page(user_agent=USER_AGENT, viewport={"width": 1440, "height": 1200})
            response = page.goto(clean_text(payload_doc.get("publisherUrl")), wait_until=args.wait_until, timeout=args.timeout_ms)
            try:
                page.wait_for_load_state("networkidle", timeout=min(args.timeout_ms, 10000))
            except PlaywrightTimeoutError:
                pass
            challenge = page.evaluate(CHALLENGE_DETECTION_SCRIPT)
            if challenge.get("blocked"):
                page.screenshot(path=str(screenshot_path), full_page=True)
                browser.close()
                report = blocked_report(payload_doc, payload_path, [challenge.get("reason", "login_or_challenge_detected")])
                report["artifacts"]["screenshot"] = str(screenshot_path)
                return report
            filled = page.evaluate(FORM_FILL_SCRIPT, normalize_payload(payload_doc.get("payload") or {}))
            submitted = bool(page.evaluate(SUBMISSION_DETECTION_SCRIPT))
            page.screenshot(path=str(screenshot_path), full_page=True)
            final_url = page.url
            title = page.title()
            browser.close()
            return {
                "generatedAt": TODAY,
                "status": "ready" if filled else "partial_ready_no_matching_visible_fields",
                "platform": clean_text(payload_doc.get("platform")),
                "publisherUrl": clean_text(payload_doc.get("publisherUrl")),
                "finalUrl": final_url,
                "httpStatus": response.status if response else None,
                "pageTitle": title,
                "payloadJson": str(payload_path),
                "submitted": submitted,
                "finalPublishUserActionRequired": True,
                "filledFields": filled,
                "missingFields": missing_fields(filled, normalize_payload(payload_doc.get("payload") or {})),
                "artifacts": {"screenshot": str(screenshot_path), "markdown": str(report_dir(out_dir) / "browser-form-fill.md")},
                "guardrails": guardrails(),
            }
    except PlaywrightError as exc:
        message = str(exc)
        if "Executable doesn't exist" in message and args.install_browser_if_missing:
            install_chromium()
            retry_args = argparse.Namespace(**vars(args))
            retry_args.install_browser_if_missing = False
            return fill_form(retry_args, payload_doc, payload_path, out_dir)
        if "Executable doesn't exist" in message:
            return error_report(payload_doc, payload_path, "Playwright Chromium is missing. Run: python -m playwright install chromium")
        return error_report(payload_doc, payload_path, f"Browser form fill failed: {message}")


def normalize_payload(payload: dict[str, Any]) -> dict[str, str]:
    tags = payload.get("tags") or []
    if isinstance(tags, list):
        tags_value = " ".join(clean_text(item) for item in tags if clean_text(item))
    else:
        tags_value = clean_text(tags)
    return {
        "title": clean_text(payload.get("title")),
        "body": clean_text(payload.get("body")),
        "tags": tags_value,
        "coverText": clean_text(payload.get("coverText")),
    }


def missing_fields(filled: list[dict[str, Any]], payload: dict[str, str]) -> list[str]:
    filled_fields = {clean_text(item.get("field")) for item in filled}
    return [field for field, value in payload.items() if value and field not in filled_fields]


def blocked_report(payload_doc: dict[str, Any], payload_path: Path, issues: list[str]) -> dict[str, Any]:
    return {
        "generatedAt": TODAY,
        "status": "blocked",
        "platform": clean_text(payload_doc.get("platform")),
        "publisherUrl": clean_text(payload_doc.get("publisherUrl")),
        "payloadJson": str(payload_path),
        "issues": issues,
        "submitted": False,
        "finalPublishUserActionRequired": True,
        "filledFields": [],
        "missingFields": list(normalize_payload(payload_doc.get("payload") or {}).keys()),
        "artifacts": {"screenshot": "", "markdown": ""},
        "guardrails": guardrails(),
    }


def error_report(payload_doc: dict[str, Any], payload_path: Path, message: str) -> dict[str, Any]:
    return {
        "generatedAt": TODAY,
        "status": "error",
        "platform": clean_text(payload_doc.get("platform")),
        "publisherUrl": clean_text(payload_doc.get("publisherUrl")),
        "payloadJson": str(payload_path),
        "error": message,
        "submitted": False,
        "finalPublishUserActionRequired": True,
        "filledFields": [],
        "missingFields": list(normalize_payload(payload_doc.get("payload") or {}).keys()),
        "artifacts": {"screenshot": "", "markdown": ""},
        "guardrails": guardrails(),
    }


def write_report(out_dir: Path, report: dict[str, Any]) -> None:
    directory = report_dir(out_dir)
    directory.mkdir(parents=True, exist_ok=True)
    markdown_path = directory / "browser-form-fill.md"
    report.setdefault("artifacts", {})
    report["artifacts"]["markdown"] = str(markdown_path)
    (directory / "browser-form-fill.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    markdown_path.write_text(render_markdown(report) + "\n", encoding="utf-8")


def render_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Browser Form Fill",
        "",
        f"- Generated: {report.get('generatedAt', '')}",
        f"- Status: `{report.get('status', '')}`",
        f"- Platform: `{report.get('platform', '')}`",
        f"- Publisher URL: {report.get('publisherUrl', '') or 'missing'}",
        f"- Submitted: `{report.get('submitted', False)}`",
        f"- Final publish user action required: `{report.get('finalPublishUserActionRequired', True)}`",
    ]
    if report.get("error"):
        lines.append(f"- Error: {report['error']}")
    if report.get("issues"):
        lines.append(f"- Issues: {', '.join(report['issues'])}")
    screenshot = (report.get("artifacts") or {}).get("screenshot")
    if screenshot:
        lines.append(f"- Screenshot: {screenshot}")
    lines.extend(["", "## Filled Fields"])
    if not report.get("filledFields"):
        lines.append("- none")
    for item in report.get("filledFields", []):
        lines.append(f"- `{item.get('field', '')}` via `{item.get('selector', '')}`")
    if report.get("missingFields"):
        lines.extend(["", "## Missing Fields"])
        lines.extend(f"- `{item}`" for item in report["missingFields"])
    lines.extend(["", "## Guardrails"])
    lines.extend(f"- {item}" for item in report.get("guardrails", []))
    return "\n".join(lines)


def install_chromium() -> None:
    subprocess.run([sys.executable, "-m", "playwright", "install", "chromium"], cwd=ROOT, check=True)


def is_local_url(parsed: Any) -> bool:
    host = (parsed.hostname or "").lower()
    return host in {"localhost", "127.0.0.1", "::1"} or host.startswith("127.")


def report_dir(out_dir: Path) -> Path:
    return out_dir / "reports/promotion-manager/browser-publish"


def clean_text(value: Any) -> str:
    return "" if value is None else re.sub(r"\s+", " ", str(value)).strip()


def guardrails() -> list[str]:
    return [
        "Visible fields only; no hidden fields, cookies, passwords, API keys, OAuth tokens, or browser storage are read.",
        "The helper does not click Publish, Submit, Post, Save, Schedule, or equivalent final action buttons.",
        "Stop for user action when login, captcha, risk control, account verification, or platform review appears.",
        "Review all fields manually before the user performs the final publish action.",
    ]


CHALLENGE_DETECTION_SCRIPT = r"""
() => {
  const clean = (value) => String(value || '').replace(/\s+/g, ' ').trim().toLowerCase();
  const text = clean(document.body ? document.body.innerText : '');
  const patterns = [
    'captcha',
    'verification code',
    'verify your account',
    'risk control',
    'account verification',
    'security check',
    '\u5b89\u5168\u9a8c\u8bc1',
    '\u9a8c\u8bc1\u7801',
    '\u8d26\u53f7\u9a8c\u8bc1',
    '\u98ce\u9669\u63a7\u5236'
  ];
  const reason = patterns.find((pattern) => text.includes(pattern));
  return {blocked: Boolean(reason), reason: reason || ''};
}
"""


SUBMISSION_DETECTION_SCRIPT = r"""
() => {
  const submittedFlag = document.body && document.body.dataset && document.body.dataset.submitted === 'yes';
  const urlLooksSubmitted = /\/published|\/success|\/post\/\d+|\/explore\/|\/video\//i.test(location.href);
  return Boolean(submittedFlag || urlLooksSubmitted);
}
"""


FORM_FILL_SCRIPT = r"""
(payload) => {
  const clean = (value) => String(value || '').replace(/\s+/g, ' ').trim();
  const candidates = Array.from(document.querySelectorAll([
    'input:not([type=hidden]):not([type=submit]):not([type=button]):not([type=file]):not([type=password])',
    'textarea',
    '[contenteditable=true]',
    '[role=textbox]'
  ].join(',')));

  const isVisible = (el) => {
    const style = window.getComputedStyle(el);
    const rect = el.getBoundingClientRect();
    return style.visibility !== 'hidden' && style.display !== 'none' && rect.width > 0 && rect.height > 0;
  };

  const labelText = (el) => {
    const id = el.getAttribute('id');
    const labels = [];
    if (id) {
      const safeId = CSS.escape(id);
      document.querySelectorAll(`label[for="${safeId}"]`).forEach((label) => labels.push(label.innerText || ''));
    }
    const wrapping = el.closest('label');
    if (wrapping) labels.push(wrapping.innerText || '');
    return labels.join(' ');
  };

  const descriptor = (el) => clean([
    el.getAttribute('name'),
    el.getAttribute('id'),
    el.getAttribute('placeholder'),
    el.getAttribute('aria-label'),
    el.getAttribute('title'),
    el.getAttribute('data-testid'),
    el.getAttribute('class'),
    labelText(el)
  ].join(' ')).toLowerCase();

  const profiles = {
    title: {
      value: clean(payload.title),
      keywords: ['title', 'headline', 'subject', 'name', '\u6807\u9898', '\u9898\u76ee'],
      preferred: ['input', 'textarea']
    },
    body: {
      value: clean(payload.body),
      keywords: ['body', 'content', 'description', 'article', 'caption', 'text', '\u6b63\u6587', '\u5185\u5bb9', '\u6587\u6848', '\u63cf\u8ff0'],
      preferred: ['textarea', '[contenteditable=true]', '[role=textbox]']
    },
    tags: {
      value: clean(payload.tags),
      keywords: ['tag', 'tags', 'hashtag', 'topic', '\u8bdd\u9898', '\u6807\u7b7e'],
      preferred: ['input']
    },
    coverText: {
      value: clean(payload.coverText),
      keywords: ['cover', 'covertext', 'thumbnail', 'poster', '\u5c01\u9762'],
      preferred: ['input', 'textarea']
    }
  };

  const matchesPreferred = (el, preferred) => preferred.some((selector) => el.matches(selector));
  const scoreElement = (el, profile, fallbackBody) => {
    if (!isVisible(el)) return -1;
    const text = descriptor(el);
    let score = 0;
    for (const keyword of profile.keywords) {
      if (text.includes(keyword.toLowerCase())) score += 10;
    }
    if (matchesPreferred(el, profile.preferred)) score += 3;
    if (fallbackBody && el.matches('textarea,[contenteditable=true],[role=textbox]')) score += 6;
    return score;
  };

  const used = new Set();
  const choose = (field, profile) => {
    const fallbackBody = field === 'body';
    let best = null;
    let bestScore = 0;
    for (const el of candidates) {
      if (used.has(el)) continue;
      const score = scoreElement(el, profile, fallbackBody);
      if (score > bestScore) {
        best = el;
        bestScore = score;
      }
    }
    if (best) used.add(best);
    return best;
  };

  const setValue = (el, value) => {
    el.focus();
    if (el.isContentEditable || el.getAttribute('contenteditable') === 'true') {
      el.textContent = value;
      el.dispatchEvent(new InputEvent('input', {bubbles: true, inputType: 'insertText', data: value}));
      el.dispatchEvent(new Event('change', {bubbles: true}));
      return;
    }
    el.value = value;
    el.dispatchEvent(new Event('input', {bubbles: true}));
    el.dispatchEvent(new Event('change', {bubbles: true}));
  };

  const selectorFor = (el) => {
    if (el.id) return `${el.tagName.toLowerCase()}#${el.id}`;
    if (el.getAttribute('name')) return `${el.tagName.toLowerCase()}[name="${el.getAttribute('name')}"]`;
    if (el.getAttribute('placeholder')) return `${el.tagName.toLowerCase()}[placeholder="${el.getAttribute('placeholder')}"]`;
    return el.tagName.toLowerCase();
  };

  const filled = [];
  for (const [field, profile] of Object.entries(profiles)) {
    if (!profile.value) continue;
    const el = choose(field, profile);
    if (!el) continue;
    setValue(el, profile.value);
    filled.push({field, value: profile.value, selector: selectorFor(el), descriptor: descriptor(el)});
  }
  return filled;
}
"""


if __name__ == "__main__":
    main()
