#!/usr/bin/env python3
"""Run safe creator/account follow-up research from the creator leaderboard."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from datetime import date
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
COMPETITOR_DIR = Path("reports/promotion-manager/competitors")
TODAY = date.today().isoformat()
PUBLIC_CONNECTOR_PLATFORMS = {"youtube", "github"}


def main() -> None:
    args = parse_args()
    out_dir = Path(args.out_dir)
    tasks_path = Path(args.tasks_json) if args.tasks_json else out_dir / COMPETITOR_DIR / "creator-follow-up-tasks.json"
    tasks = load_tasks(tasks_path, args.limit)
    results, records = run_tasks(args, out_dir, tasks)
    write_outputs(out_dir, tasks_path, results, records, args.dry_run)
    print(f"Creator follow-up results written to: {(report_dir(out_dir) / 'creator-follow-up-results.json').resolve()}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run safe public creator/account follow-up research and queue manual evidence requests.")
    parser.add_argument("--tasks-json", default="", help="creator-follow-up-tasks.json generated by creator_leaderboard.py.")
    parser.add_argument("--out-dir", default="./promotion-output")
    parser.add_argument("--limit", type=int, default=20)
    parser.add_argument("--top-n", type=int, default=5, help="Per-creator official/public connector result count.")
    parser.add_argument("--dry-run", action="store_true", help="Plan public creator research without fetching APIs.")
    parser.add_argument("--youtube-search-json", default="", help="Test fixture for YouTube search.list response.")
    parser.add_argument("--youtube-videos-json", default="", help="Test fixture for YouTube videos.list response.")
    parser.add_argument("--youtube-channels-json", default="", help="Test fixture for YouTube channels.list response.")
    parser.add_argument("--github-search-json", default="", help="Test fixture for GitHub repository search response.")
    return parser.parse_args()


def load_tasks(path: Path, limit: int) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8-sig"))
    except json.JSONDecodeError:
        return []
    tasks = data.get("tasks", []) if isinstance(data, dict) else []
    return [task for task in tasks if isinstance(task, dict)][: max(limit, 0)]


def run_tasks(args: argparse.Namespace, out_dir: Path, tasks: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    results = []
    records = []
    for task in tasks:
        if can_run_public_connector(task):
            result, task_records = run_public_connector(args, out_dir, task)
        else:
            result, task_records = create_evidence_request(out_dir, task), []
        results.append(result)
        records.extend(task_records)
    return results, records


def can_run_public_connector(task: dict[str, Any]) -> bool:
    return task.get("trackingMode") == "public_or_official_research_candidate" and str(task.get("platform") or "") in PUBLIC_CONNECTOR_PLATFORMS


def run_public_connector(args: argparse.Namespace, out_dir: Path, task: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    platform = str(task.get("platform") or "")
    creator_name = normalize_space(task.get("creatorName") or "")
    task_id = safe_slug(str(task.get("id") or task.get("creatorId") or "creator-follow-up"))
    task_out_dir = report_dir(out_dir) / "creator-follow-ups" / task_id
    query = connector_query(platform, creator_name)
    command = [
        sys.executable,
        str(SCRIPTS / "competitor_collector.py"),
        "--platform",
        platform,
        "--query",
        query,
        "--top-n",
        str(max(args.top_n, 0)),
        "--out-dir",
        str(task_out_dir),
    ]
    append_fixture_args(command, args, platform)
    result = base_result(task, "official_or_public_creator_connector", command)
    if not creator_name or creator_name.lower().startswith("unknown"):
        result.update({"status": "blocked", "reason": "Creator identity is unknown; browser-visible evidence is required first.", "recordCount": 0})
        return result, []
    if args.dry_run:
        result.update({"status": "dry_run", "reason": "Public creator connector planned but not executed because --dry-run was supplied.", "recordCount": 0})
        return result, []

    completed = subprocess.run(command, cwd=ROOT, capture_output=True, text=True, check=False)
    report_path = task_out_dir / COMPETITOR_DIR / "auto-collected-competitors.json"
    records = records_from_collection(report_path, task)
    result.update(
        {
            "status": "ready" if completed.returncode == 0 and report_path.exists() else "error",
            "exitCode": completed.returncode,
            "stdoutTail": tail(completed.stdout),
            "stderrTail": tail(completed.stderr),
            "collectionReport": str(report_path) if report_path.exists() else "",
            "recordCount": len(records),
        }
    )
    return result, records


def create_evidence_request(out_dir: Path, task: dict[str, Any]) -> dict[str, Any]:
    task_id = safe_slug(str(task.get("id") or task.get("creatorId") or "creator-follow-up"))
    request_dir = report_dir(out_dir) / "creator-follow-ups/manual-evidence"
    request_dir.mkdir(parents=True, exist_ok=True)
    request_path = request_dir / f"{task_id}.md"
    request_path.write_text(render_evidence_request(task) + "\n", encoding="utf-8")
    result = base_result(task, "browser_or_manual_creator_evidence", [])
    result.update(
        {
            "status": "queued_manual_evidence",
            "reason": "Creator follow-up requires browser-visible profile evidence, official access, screenshots, transcripts, or user exports.",
            "evidenceRequest": str(request_path),
            "recordCount": 0,
        }
    )
    return result


def append_fixture_args(command: list[str], args: argparse.Namespace, platform: str) -> None:
    if platform == "youtube":
        append_if_present(command, "--youtube-search-json", args.youtube_search_json)
        append_if_present(command, "--youtube-videos-json", args.youtube_videos_json)
        append_if_present(command, "--youtube-channels-json", args.youtube_channels_json)
    if platform == "github":
        append_if_present(command, "--github-search-json", args.github_search_json)


def records_from_collection(path: Path, task: dict[str, Any]) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    try:
        report = json.loads(path.read_text(encoding="utf-8-sig"))
    except json.JSONDecodeError:
        return []
    records = []
    for record in report.get("records", []):
        if not isinstance(record, dict):
            continue
        enriched = dict(record)
        enriched["sourceCreatorTask"] = {
            "id": task.get("id", ""),
            "creatorId": task.get("creatorId", ""),
            "creatorName": task.get("creatorName", ""),
            "priority": task.get("priority"),
            "platform": task.get("platform", ""),
            "sampleUrls": task.get("sampleUrls", []),
        }
        records.append(enriched)
    return records


def write_outputs(out_dir: Path, tasks_path: Path, results: list[dict[str, Any]], records: list[dict[str, Any]], dry_run: bool) -> None:
    directory = report_dir(out_dir)
    directory.mkdir(parents=True, exist_ok=True)
    result_report = {
        "generatedAt": TODAY,
        "tasksJson": str(tasks_path),
        "dryRun": dry_run,
        "recordCount": len(results),
        "results": results,
        "summary": summarize_results(results),
        "guardrails": guardrails(),
    }
    library = {
        "generatedAt": TODAY,
        "recordCount": len(records),
        "records": records,
        "aggregatePatterns": aggregate_records(records),
        "guardrails": guardrails(),
    }
    (directory / "creator-follow-up-results.json").write_text(json.dumps(result_report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (directory / "creator-follow-up-results.md").write_text(render_results_markdown(result_report) + "\n", encoding="utf-8")
    (directory / "creator-deep-library.json").write_text(json.dumps(library, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (directory / "creator-deep-library.md").write_text(render_library_markdown(library) + "\n", encoding="utf-8")


def base_result(task: dict[str, Any], mode: str, command: list[Any]) -> dict[str, Any]:
    return {
        "taskId": task.get("id", ""),
        "creatorId": task.get("creatorId", ""),
        "creatorName": task.get("creatorName", ""),
        "platform": task.get("platform", ""),
        "priority": task.get("priority"),
        "trackingMode": task.get("trackingMode", ""),
        "mode": mode,
        "sampleUrls": task.get("sampleUrls", []),
        "command": display_command([str(item) for item in command]),
    }


def connector_query(platform: str, creator_name: str) -> str:
    if platform == "github":
        return f"user:{creator_name}"
    return creator_name


def summarize_results(results: list[dict[str, Any]]) -> dict[str, Any]:
    statuses: dict[str, int] = {}
    modes: dict[str, int] = {}
    imported = 0
    for result in results:
        statuses[str(result.get("status", "unknown"))] = statuses.get(str(result.get("status", "unknown")), 0) + 1
        modes[str(result.get("mode", "unknown"))] = modes.get(str(result.get("mode", "unknown")), 0) + 1
        imported += int(result.get("recordCount") or 0)
    return {"statuses": dict(sorted(statuses.items())), "modes": dict(sorted(modes.items())), "importedRecords": imported}


def aggregate_records(records: list[dict[str, Any]]) -> dict[str, Any]:
    pattern_counts: dict[str, int] = {}
    creators = sorted({str(record.get("creatorName") or "unknown") for record in records})
    platforms = sorted({str(record.get("platform") or "unknown") for record in records})
    for record in records:
        for pattern in record.get("reusablePatterns", []):
            pattern_counts[str(pattern)] = pattern_counts.get(str(pattern), 0) + 1
    return {
        "platforms": platforms,
        "creators": creators,
        "recordsWithObservedMetrics": sum(1 for record in records if record.get("visibleMetrics")),
        "patternCounts": dict(sorted(pattern_counts.items())),
        "titleExamples": [record.get("title", "") for record in records[:10]],
    }


def render_evidence_request(task: dict[str, Any]) -> str:
    lines = [
        "# Creator Follow-Up Evidence Request",
        "",
        f"- Task: {task.get('id', '')}",
        f"- Creator: {task.get('creatorName', '')}",
        f"- Platform: {task.get('platform', '')}",
        f"- Tracking mode: `{task.get('trackingMode', '')}`",
        f"- Status: `{task.get('status', '')}`",
        "",
        "## Sample URLs",
    ]
    sample_urls = task.get("sampleUrls") if isinstance(task.get("sampleUrls"), list) else []
    lines.extend(f"- {url}" for url in sample_urls) if sample_urls else lines.append("- missing")
    lines.extend(["", "## Required Evidence"])
    for item in task.get("requiredEvidence", []):
        lines.append(f"- {item}")
    lines.extend(["", "## Guardrails"])
    lines.extend(f"- {item}" for item in guardrails())
    return "\n".join(lines)


def render_results_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Creator Follow-Up Results",
        "",
        f"- Generated: {report['generatedAt']}",
        f"- Dry run: {report['dryRun']}",
        f"- Tasks: {report['recordCount']}",
        f"- Imported records: {report['summary']['importedRecords']}",
        "",
        "## Results",
    ]
    for result in report["results"]:
        lines.extend(
            [
                "",
                f"### {result.get('taskId', 'task')} - {result.get('creatorName', '')}",
                f"- Platform: {result.get('platform', '')}",
                f"- Status: `{result.get('status', '')}`",
                f"- Mode: `{result.get('mode', '')}`",
                f"- Imported records: {result.get('recordCount', 0)}",
            ]
        )
        if result.get("reason"):
            lines.append(f"- Reason: {result['reason']}")
        if result.get("evidenceRequest"):
            lines.append(f"- Evidence request: {result['evidenceRequest']}")
    lines.extend(["", "## Guardrails"])
    lines.extend(f"- {item}" for item in report["guardrails"])
    return "\n".join(lines)


def render_library_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Creator Deep Library",
        "",
        f"- Generated: {report['generatedAt']}",
        f"- Records: {report['recordCount']}",
        f"- Platforms: {', '.join(report['aggregatePatterns']['platforms']) if report['aggregatePatterns']['platforms'] else 'none'}",
        "",
        "## Records",
    ]
    for record in report["records"]:
        lines.extend(
            [
                "",
                f"### {record.get('id', 'record')} - {record.get('title', '')}",
                f"- Platform: {record.get('platform', '')}",
                f"- Creator: {record.get('creatorName') or 'unknown'}",
                f"- URL: {record.get('url') or 'unknown'}",
                f"- Hook: {record.get('hook') or 'needs manual review'}",
            ]
        )
    lines.extend(["", "## Guardrails"])
    lines.extend(f"- {item}" for item in report["guardrails"])
    return "\n".join(lines)


def guardrails() -> list[str]:
    return [
        "Run automatic creator follow-up only through supported official/public connectors.",
        "Use browser-visible evidence, screenshots, transcripts, official APIs, or user exports for protected platforms.",
        "Do not bypass captcha, login prompts, account verification, platform rate limits, or risk controls.",
        "Do not store cookies, passwords, API keys, OAuth tokens, or hidden browser tokens.",
        "Do not fabricate creator metrics, platform metrics, orders, revenue, or published URLs.",
    ]


def report_dir(out_dir: Path) -> Path:
    return out_dir / COMPETITOR_DIR


def append_if_present(command: list[str], flag: str, value: str) -> None:
    if value:
        command.extend([flag, value])


def normalize_space(value: Any) -> str:
    return re.sub(r"\s+", " ", str(value)).strip()


def safe_slug(value: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_.-]+", "-", value.strip()).strip("-") or "creator-follow-up"


def display_command(command: list[str]) -> list[str]:
    return ["python" if item == sys.executable else item for item in command]


def tail(value: str, limit: int = 1200) -> str:
    value = value.strip()
    return value if len(value) <= limit else value[-limit:]


if __name__ == "__main__":
    main()
