#!/usr/bin/env python3
"""Execute safe follow-up capture tasks from the viral material library."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import urllib.parse
from datetime import date
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
COMPETITOR_DIR = Path("reports/promotion-manager/competitors")
TODAY = date.today().isoformat()


def main() -> None:
    args = parse_args()
    out_dir = Path(args.out_dir)
    tasks_path = Path(args.tasks_json) if args.tasks_json else out_dir / COMPETITOR_DIR / "follow-up-capture-tasks.json"
    tasks = load_tasks(tasks_path, args.limit)
    results, deep_records = run_tasks(args, out_dir, tasks)
    write_outputs(out_dir, tasks_path, results, deep_records, args.dry_run)
    print(f"Follow-up capture results written to: {(report_dir(out_dir) / 'follow-up-capture-results.json').resolve()}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run safe public follow-up captures and create evidence requests for manual/browser-assisted tasks.")
    parser.add_argument("--tasks-json", default="", help="follow-up-capture-tasks.json generated by viral_content_library.py.")
    parser.add_argument("--out-dir", default="./promotion-output")
    parser.add_argument("--limit", type=int, default=20)
    parser.add_argument("--dry-run", action="store_true", help="Plan public captures without fetching URLs.")
    parser.add_argument("--allow-localhost", action="store_true", help="Allow localhost URLs for local fixtures/tests only.")
    parser.add_argument(
        "--capture-browser-assisted",
        action="store_true",
        help="Attempt safe browser-visible snapshots for queued browser-assisted tasks with public URLs.",
    )
    parser.add_argument(
        "--install-browser-if-missing",
        action="store_true",
        help="Allow browser_snapshot.py to run the official Playwright Chromium install when browser-assisted capture is requested.",
    )
    parser.add_argument(
        "--sample-video-frames",
        action="store_true",
        help="After a safe follow-up capture, sample browser-visible video metadata and frame screenshots for video platforms.",
    )
    parser.add_argument("--video-sample-count", type=int, default=5)
    return parser.parse_args()


def load_tasks(path: Path, limit: int) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8-sig"))
    except json.JSONDecodeError:
        return []
    tasks = data.get("tasks", []) if isinstance(data, dict) else []
    return [task for task in tasks if isinstance(task, dict)][: max(limit, 0)]


def run_tasks(args: argparse.Namespace, out_dir: Path, tasks: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    results = []
    deep_records = []
    for task in tasks:
        if task.get("mode") == "public_url_capture_candidate":
            result, records = run_public_capture(args, out_dir, task)
        elif args.capture_browser_assisted and task.get("mode") == "browser_assisted_capture_required":
            result, records = run_browser_visible_capture(args, out_dir, task)
        else:
            result, records = create_evidence_request(out_dir, task), []
        results.append(result)
        deep_records.extend(records)
    return results, deep_records


def run_public_capture(args: argparse.Namespace, out_dir: Path, task: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    url = str(task.get("url") or "")
    platform = str(task.get("platform") or "auto")
    task_id = safe_slug(str(task.get("id") or task.get("materialId") or "follow-up"))
    task_out_dir = report_dir(out_dir) / "follow-up-captures" / task_id
    validation_issue = validate_public_capture_url(url, args.allow_localhost)
    command = [
        sys.executable,
        str(SCRIPTS / "competitor_intake.py"),
        "--url",
        url,
        "--platform",
        platform,
        "--out-dir",
        str(task_out_dir),
    ]
    base = base_result(task, "public_url_capture_candidate", command)
    if validation_issue:
        base.update({"status": "blocked", "reason": validation_issue})
        return base, []
    if args.dry_run:
        base.update({"status": "dry_run", "reason": "Public capture planned but not executed because --dry-run was supplied."})
        return base, []

    result = subprocess.run(command, cwd=ROOT, capture_output=True, text=True, check=False)
    imported_path = task_out_dir / COMPETITOR_DIR / "imported-competitors.json"
    base.update(
        {
            "status": "ready" if result.returncode == 0 and imported_path.exists() else "error",
            "exitCode": result.returncode,
            "stdoutTail": tail(result.stdout),
            "stderrTail": tail(result.stderr),
            "importedCompetitors": str(imported_path) if imported_path.exists() else "",
        }
    )
    records = records_from_import(imported_path, task)
    base["recordCount"] = len(records)
    video_sample = attach_video_sample(args, task, task_out_dir, base)
    enrich_records_with_video_sample(records, video_sample)
    return base, records


def run_browser_visible_capture(args: argparse.Namespace, out_dir: Path, task: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    url = str(task.get("url") or "")
    platform = str(task.get("platform") or "auto")
    task_id = safe_slug(str(task.get("id") or task.get("materialId") or "follow-up"))
    task_out_dir = report_dir(out_dir) / "follow-up-captures" / task_id
    task_out_dir.mkdir(parents=True, exist_ok=True)
    snapshot_path = task_out_dir / "browser-visible-snapshot.json"
    validation_issue = validate_public_capture_url(url, args.allow_localhost)
    snapshot_command = [
        sys.executable,
        str(SCRIPTS / "browser_snapshot.py"),
        "--url",
        url,
        "--out-file",
        str(snapshot_path),
        "--out-dir",
        str(task_out_dir),
    ]
    if args.install_browser_if_missing:
        snapshot_command.append("--install-browser-if-missing")
    import_command = [
        sys.executable,
        str(SCRIPTS / "competitor_intake.py"),
        "--json-file",
        str(snapshot_path),
        "--platform",
        platform,
        "--out-dir",
        str(task_out_dir),
    ]
    base = base_result(task, "browser_visible_capture", snapshot_command)
    base["importCommand"] = display_command(import_command)
    if validation_issue:
        return blocked_browser_capture(out_dir, task, base, validation_issue, str(snapshot_path)), []
    if args.dry_run:
        base.update({"status": "dry_run", "reason": "Browser-visible capture planned but not executed because --dry-run was supplied.", "browserSnapshot": str(snapshot_path), "recordCount": 0})
        return base, []

    snapshot_result = subprocess.run(snapshot_command, cwd=ROOT, capture_output=True, text=True, check=False)
    base.update(
        {
            "snapshotExitCode": snapshot_result.returncode,
            "snapshotStdoutTail": tail(snapshot_result.stdout),
            "snapshotStderrTail": tail(snapshot_result.stderr),
            "browserSnapshot": str(snapshot_path) if snapshot_path.exists() else "",
        }
    )
    if snapshot_result.returncode != 0 or not snapshot_path.exists():
        base.update({"status": "error", "reason": "Browser-visible snapshot failed before import.", "recordCount": 0})
        return base, []
    unsafe_issue = unsafe_snapshot_issue(snapshot_path)
    if unsafe_issue:
        return blocked_browser_capture(out_dir, task, base, unsafe_issue, str(snapshot_path)), []

    import_result = subprocess.run(import_command, cwd=ROOT, capture_output=True, text=True, check=False)
    imported_path = task_out_dir / COMPETITOR_DIR / "imported-competitors.json"
    base.update(
        {
            "status": "ready" if import_result.returncode == 0 and imported_path.exists() else "error",
            "importExitCode": import_result.returncode,
            "importStdoutTail": tail(import_result.stdout),
            "importStderrTail": tail(import_result.stderr),
            "importedCompetitors": str(imported_path) if imported_path.exists() else "",
        }
    )
    records = records_from_import(imported_path, task)
    base["recordCount"] = len(records)
    video_sample = attach_video_sample(args, task, task_out_dir, base)
    enrich_records_with_video_sample(records, video_sample)
    return base, records


def attach_video_sample(args: argparse.Namespace, task: dict[str, Any], task_out_dir: Path, result: dict[str, Any]) -> dict[str, Any] | None:
    if not args.sample_video_frames or not should_sample_video(task):
        return None
    url = str(task.get("url") or "")
    platform = str(task.get("platform") or "auto")
    command = [
        sys.executable,
        str(SCRIPTS / "browser_video_sampler.py"),
        "--url",
        url,
        "--platform",
        platform,
        "--sample-count",
        str(args.video_sample_count),
        "--out-dir",
        str(task_out_dir),
    ]
    if args.allow_localhost:
        command.append("--allow-localhost")
    if args.install_browser_if_missing:
        command.append("--install-browser-if-missing")
    video_result = subprocess.run(command, cwd=ROOT, capture_output=True, text=True, check=False)
    report_path = task_out_dir / COMPETITOR_DIR / "video-sampling/browser-video-sampler.json"
    payload = read_json(report_path)
    sample = {
        "status": payload.get("status", "error") if report_path.exists() and video_result.returncode == 0 else "error",
        "report": str(report_path) if report_path.exists() else "",
        "videoCount": payload.get("videoCount", 0),
        "frameCount": len(payload.get("frames", [])) if isinstance(payload.get("frames"), list) else 0,
        "contentEvidence": payload.get("contentEvidence") if isinstance(payload.get("contentEvidence"), dict) else {},
        "visibleTranscriptHints": payload.get("visibleTranscriptHints") if isinstance(payload.get("visibleTranscriptHints"), list) else [],
        "exitCode": video_result.returncode,
        "command": display_command(command),
        "stdoutTail": tail(video_result.stdout),
        "stderrTail": tail(video_result.stderr),
    }
    result["videoSample"] = sample
    return sample


def enrich_records_with_video_sample(records: list[dict[str, Any]], video_sample: dict[str, Any] | None) -> None:
    if not video_sample or video_sample.get("status") != "ready":
        return
    evidence = video_sample_record(video_sample)
    for record in records:
        record["videoSampleEvidence"] = evidence
        deconstruction = record.get("contentDeconstruction") if isinstance(record.get("contentDeconstruction"), dict) else {}
        deconstruction["videoEvidence"] = {
            "status": evidence["status"],
            "report": evidence["report"],
            "videoCount": evidence["videoCount"],
            "frameCount": evidence["frameCount"],
            "frameScreenshots": evidence["frameScreenshots"],
            "visibleTranscriptHints": evidence["visibleTranscriptHints"],
            "guardrail": "Browser-visible frame evidence only; no private stream download, token extraction, or inferred audio transcript.",
        }
        record["contentDeconstruction"] = deconstruction


def video_sample_record(video_sample: dict[str, Any]) -> dict[str, Any]:
    content_evidence = video_sample.get("contentEvidence") if isinstance(video_sample.get("contentEvidence"), dict) else {}
    video_evidence = content_evidence.get("videoEvidence") if isinstance(content_evidence.get("videoEvidence"), dict) else {}
    frames = video_evidence.get("frames") if isinstance(video_evidence.get("frames"), list) else []
    frame_screenshots = [
        {
            "index": frame.get("index"),
            "time": frame.get("time"),
            "screenshot": frame.get("screenshot", ""),
            "status": frame.get("status", ""),
        }
        for frame in frames
        if isinstance(frame, dict)
    ]
    return {
        "status": video_sample.get("status", ""),
        "report": video_sample.get("report", ""),
        "videoCount": video_sample.get("videoCount", 0),
        "frameCount": video_sample.get("frameCount", 0),
        "frameScreenshots": frame_screenshots,
        "visibleTranscriptHints": [str(item) for item in video_sample.get("visibleTranscriptHints", [])],
        "contentExcerpt": content_evidence.get("contentExcerpt", ""),
        "suggestedNextStep": content_evidence.get("suggestedNextStep", ""),
    }


def should_sample_video(task: dict[str, Any]) -> bool:
    platform = str(task.get("platform") or "").lower()
    content_format = str(task.get("contentFormat") or task.get("format") or "").lower()
    url = str(task.get("url") or "").lower()
    if platform in {"youtube", "douyin", "tiktok"}:
        return True
    if "video" in content_format:
        return True
    return any(host in url for host in ["youtube.com", "youtu.be", "douyin.com", "tiktok.com"])


def blocked_browser_capture(out_dir: Path, task: dict[str, Any], base: dict[str, Any], reason: str, snapshot_path: str) -> dict[str, Any]:
    request = create_evidence_request(out_dir, task)
    base.update(
        {
            "status": "queued_manual_evidence",
            "reason": reason,
            "browserSnapshot": snapshot_path,
            "evidenceRequest": request.get("evidenceRequest", ""),
            "recordCount": 0,
        }
    )
    return base


def create_evidence_request(out_dir: Path, task: dict[str, Any]) -> dict[str, Any]:
    task_id = safe_slug(str(task.get("id") or task.get("materialId") or "follow-up"))
    request_dir = report_dir(out_dir) / "follow-up-captures/manual-evidence"
    request_dir.mkdir(parents=True, exist_ok=True)
    request_path = request_dir / f"{task_id}.md"
    request_path.write_text(render_evidence_request(task) + "\n", encoding="utf-8")
    result = base_result(task, str(task.get("mode") or "manual"), task.get("command") if isinstance(task.get("command"), list) else [])
    status = "blocked" if str(task.get("mode")) in {"manual_url_required", "unsupported_or_private_url"} else "queued_manual_evidence"
    result.update(
        {
            "status": status,
            "reason": task.get("reason") or "Manual or browser-visible evidence is required before deep capture.",
            "evidenceRequest": str(request_path),
            "recordCount": 0,
        }
    )
    return result


def records_from_import(path: Path, task: dict[str, Any]) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    try:
        report = json.loads(path.read_text(encoding="utf-8-sig"))
    except json.JSONDecodeError:
        return []
    records = []
    for record in report.get("records", []):
        if not isinstance(record, dict):
            continue
        enriched = dict(record)
        enriched["sourceFollowUpTask"] = {
            "id": task.get("id"),
            "materialId": task.get("materialId"),
            "priority": task.get("priority"),
            "title": task.get("title"),
            "url": task.get("url"),
        }
        records.append(enriched)
    return records


def write_outputs(out_dir: Path, tasks_path: Path, results: list[dict[str, Any]], deep_records: list[dict[str, Any]], dry_run: bool) -> None:
    directory = report_dir(out_dir)
    directory.mkdir(parents=True, exist_ok=True)
    result_report = {
        "generatedAt": TODAY,
        "tasksJson": str(tasks_path),
        "dryRun": dry_run,
        "recordCount": len(results),
        "results": results,
        "summary": summarize_results(results),
        "guardrails": guardrails(),
    }
    deep_report = {
        "generatedAt": TODAY,
        "recordCount": len(deep_records),
        "records": deep_records,
        "aggregatePatterns": aggregate_deep_records(deep_records),
        "guardrails": guardrails(),
    }
    (directory / "follow-up-capture-results.json").write_text(json.dumps(result_report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (directory / "follow-up-capture-results.md").write_text(render_results_markdown(result_report) + "\n", encoding="utf-8")
    (directory / "deep-competitor-library.json").write_text(json.dumps(deep_report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (directory / "deep-competitor-library.md").write_text(render_deep_markdown(deep_report) + "\n", encoding="utf-8")


def base_result(task: dict[str, Any], mode: str, command: list[Any]) -> dict[str, Any]:
    return {
        "taskId": task.get("id", ""),
        "materialId": task.get("materialId", ""),
        "priority": task.get("priority"),
        "platform": task.get("platform", ""),
        "title": task.get("title", ""),
        "url": task.get("url", ""),
        "mode": mode,
        "command": display_command([str(item) for item in command]),
    }


def validate_public_capture_url(url: str, allow_localhost: bool) -> str:
    parsed = urllib.parse.urlparse(url)
    if parsed.scheme not in {"http", "https"} or not parsed.netloc:
        return "URL is not a public HTTP(S) URL."
    host = parsed.hostname or ""
    if host in {"localhost", "127.0.0.1", "::1"} and not allow_localhost:
        return "Localhost URLs are blocked unless --allow-localhost is supplied for fixtures/tests."
    lowered = url.lower()
    if any(marker in lowered for marker in ["/login", "/signin", "/captcha", "/challenge", "/editor", "/draft", "/preview"]):
        return "URL looks like login, captcha, editor, draft, or preview flow."
    return ""


def unsafe_snapshot_issue(path: Path) -> str:
    try:
        data = json.loads(path.read_text(encoding="utf-8-sig"))
    except (OSError, json.JSONDecodeError):
        return "Browser snapshot could not be parsed safely."
    text = " ".join(str(data.get(key) or "") for key in ["url", "title", "description", "text"]).lower()
    blocked_patterns = [
        "captcha",
        "challenge",
        "verify you are human",
        "please sign in to continue",
        "login required",
        "access denied",
        "请先登录",
        "登录后查看",
        "验证码",
        "安全验证",
        "访问受限",
        "请完成验证",
    ]
    if any(pattern in text for pattern in blocked_patterns):
        return "Browser snapshot appears to be login, captcha, verification, or access-denied content."
    return ""


def summarize_results(results: list[dict[str, Any]]) -> dict[str, Any]:
    statuses: dict[str, int] = {}
    modes: dict[str, int] = {}
    imported = 0
    video_sample_runs = 0
    video_sample_ready = 0
    video_sample_frames = 0
    for result in results:
        statuses[str(result.get("status", "unknown"))] = statuses.get(str(result.get("status", "unknown")), 0) + 1
        modes[str(result.get("mode", "unknown"))] = modes.get(str(result.get("mode", "unknown")), 0) + 1
        imported += int(result.get("recordCount") or 0)
        video_sample = result.get("videoSample")
        if isinstance(video_sample, dict):
            video_sample_runs += 1
            if video_sample.get("status") == "ready":
                video_sample_ready += 1
            video_sample_frames += int(video_sample.get("frameCount") or 0)
    return {
        "statuses": dict(sorted(statuses.items())),
        "modes": dict(sorted(modes.items())),
        "importedRecords": imported,
        "videoSampleRuns": video_sample_runs,
        "videoSampleReady": video_sample_ready,
        "videoSampleFrames": video_sample_frames,
    }


def read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8-sig"))
    except (OSError, json.JSONDecodeError):
        return {}
    return data if isinstance(data, dict) else {}


def aggregate_deep_records(records: list[dict[str, Any]]) -> dict[str, Any]:
    platforms = sorted({str(record.get("platform") or "unknown") for record in records})
    pattern_counts: dict[str, int] = {}
    video_backed_records = 0
    video_sample_frames = 0
    for record in records:
        for pattern in record.get("reusablePatterns", []):
            pattern_counts[str(pattern)] = pattern_counts.get(str(pattern), 0) + 1
        sample = record.get("videoSampleEvidence") if isinstance(record.get("videoSampleEvidence"), dict) else {}
        if sample:
            video_backed_records += 1
            video_sample_frames += int(sample.get("frameCount") or 0)
    return {
        "platforms": platforms,
        "titles": [record.get("title", "") for record in records[:10]],
        "recordsWithObservedMetrics": sum(1 for record in records if record.get("visibleMetrics")),
        "recordsWithVideoSampleEvidence": video_backed_records,
        "videoSampleFrames": video_sample_frames,
        "patternCounts": dict(sorted(pattern_counts.items())),
    }


def report_dir(out_dir: Path) -> Path:
    return out_dir / COMPETITOR_DIR


def render_evidence_request(task: dict[str, Any]) -> str:
    lines = [
        "# Follow-Up Evidence Request",
        "",
        f"- Task: {task.get('id', '')}",
        f"- Material: {task.get('materialId', '')}",
        f"- Platform: {task.get('platform', '')}",
        f"- Title: {task.get('title', '')}",
        f"- URL: {task.get('url') or 'missing'}",
        f"- Mode: `{task.get('mode', '')}`",
        f"- Reason: {task.get('reason', '')}",
        "",
        "## Required Evidence",
    ]
    for item in task.get("requiredEvidence", []):
        lines.append(f"- {item}")
    lines.extend(
        [
            "",
            "## Safe Import Command",
            "",
            "Use copied browser-visible text, transcript, or official/user export only.",
            "",
            "```bash",
            f"python scripts/competitor_intake.py --text-file \"<visible-evidence.txt>\" --platform {task.get('platform', 'auto')} --out-dir \"<promotion-output>\"",
            "```",
        ]
    )
    return "\n".join(lines)


def render_results_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Follow-Up Capture Results",
        "",
        f"- Generated: {report['generatedAt']}",
        f"- Dry run: {report['dryRun']}",
        f"- Tasks: {report['recordCount']}",
        f"- Imported records: {report['summary']['importedRecords']}",
        f"- Video sample runs: {report['summary'].get('videoSampleRuns', 0)}",
        f"- Video sample frames: {report['summary'].get('videoSampleFrames', 0)}",
        "",
        "## Results",
    ]
    for result in report["results"]:
        lines.extend(
            [
                "",
                f"### {result.get('taskId', 'task')} - {result.get('platform', '')}",
                f"- Status: `{result.get('status', '')}`",
                f"- Mode: `{result.get('mode', '')}`",
                f"- Title: {result.get('title', '')}",
                f"- URL: {result.get('url') or 'unknown'}",
                f"- Imported records: {result.get('recordCount', 0)}",
            ]
        )
        if result.get("reason"):
            lines.append(f"- Reason: {result['reason']}")
        if result.get("evidenceRequest"):
            lines.append(f"- Evidence request: {result['evidenceRequest']}")
        video_sample = result.get("videoSample")
        if isinstance(video_sample, dict):
            lines.append(f"- Video sample: `{video_sample.get('status', '')}`")
            lines.append(f"- Video sample frames: {video_sample.get('frameCount', 0)}")
            if video_sample.get("report"):
                lines.append(f"- Video sample report: {video_sample['report']}")
    lines.extend(["", "## Guardrails"])
    lines.extend(f"- {item}" for item in report["guardrails"])
    return "\n".join(lines)


def render_deep_markdown(report: dict[str, Any]) -> str:
    lines = [
        "# Deep Competitor Library",
        "",
        f"- Generated: {report['generatedAt']}",
        f"- Records: {report['recordCount']}",
        f"- Platforms: {', '.join(report['aggregatePatterns']['platforms']) if report['aggregatePatterns']['platforms'] else 'none'}",
        "",
        "## Records",
    ]
    for record in report["records"]:
        lines.extend(
            [
                "",
                f"### {record.get('id', 'record')} - {record.get('title', '')}",
                f"- Platform: {record.get('platform', '')}",
                f"- Creator: {record.get('creatorName') or 'unknown'}",
                f"- URL: {record.get('url') or 'unknown'}",
                f"- Hook: {record.get('hook') or 'needs manual review'}",
                f"- CTA: {record.get('cta') or 'none observed'}",
            ]
        )
        sample = record.get("videoSampleEvidence") if isinstance(record.get("videoSampleEvidence"), dict) else {}
        if sample:
            lines.append(f"- Video sample frames: {sample.get('frameCount', 0)}")
            if sample.get("report"):
                lines.append(f"- Video sample report: {sample['report']}")
    lines.extend(["", "## Guardrails"])
    lines.extend(f"- {item}" for item in report["guardrails"])
    return "\n".join(lines)


def guardrails() -> list[str]:
    return [
        "Only public URL capture candidates are fetched automatically.",
        "Manual/browser-assisted tasks require user-provided visible text, screenshots, transcripts, official APIs, or exports.",
        "Do not bypass captcha, login prompts, account verification, platform rate limits, or risk controls.",
        "Do not store cookies, passwords, API keys, OAuth tokens, or hidden browser tokens.",
        "Do not fabricate views, likes, comments, orders, revenue, or published URLs.",
    ]


def display_command(command: list[str]) -> list[str]:
    return ["python" if item == sys.executable else item for item in command]


def tail(value: str, limit: int = 1200) -> str:
    value = value.strip()
    return value if len(value) <= limit else value[-limit:]


def safe_slug(value: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_.-]+", "-", value.strip()).strip("-") or "follow-up"


if __name__ == "__main__":
    main()
